---
- hosts: ocean
  vars:
    app_dir: /var/www/gitforms
    user: appwww
    branch: master

  tasks:
    - name: create directory for project
      file:
        path={{ app_dir }}
        owner={{ user }}
        group={{ user }}
        mode=0755
        state=directory

    # - name: Ensure github is in the known_hosts file
    #   known_hosts: host=github.com state=present

    - name: checkout repo
      tags: code_update
      remote_user: "{{ user }}"
      git: repo=https://github.com/inem/gitforms
        dest={{app_dir}}
        accept_hostkey=yes
        version={{branch}}
      # notify:
      # - touch restart.txt

    - name: ensure tmp/pids exist
      file:
        path=/var/www/gitforms/tmp/pids
        owner={{ user }}
        group=www-data
        mode=0755
        state=directory

    - name: ensure tmp/pids exist
      file:
        path=/var/www/gitforms/tmp/sockets
        owner={{ user }}
        group=www-data
        mode=0755
        state=directory

    - name: ensure log exist
      file:
        path=/var/www/gitforms/log
        owner={{ user }}
        group=www-data
        mode=0755
        state=directory


    - name: Install gems
      command: bash -lc "bundle install --path vendor/bundle"
        chdir={{ app_dir }}